language:
  - cpp
  
before_install:
  - pip install --user cpp-coveralls
        
script:
  - qmake
  - make

after_success:
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  
cache:
  directories:
    - '$HOME/.sonar/cache'
  
notifications:
  email: false
